### ISSUE TITLE
Check script fails if subcommands are not installed

### ISSUE THREAD

**Issue by eadgbear** [KyleU/generust#1]
Starting from a fresh dev environment, bootstrap/check script fails unless the following are installed:

- cargo-count
- cargo-outdated
- cargo-deps
- cargo-audit
- sass

It also requires the nightly toolchain.

**Comment by kyleu** [comment]
Thanks for noticing that, I should have tested with a new machine. The `check` call has been removed from `bootstrap`, and comments have been added to call out cargo dependencies and the requirement for nightly.
